SERVICE:
    SERVICE_IP: "0.0.0.0"
    SERVICE_PORT: 5055
    LOG_PATH: "logfile"
    # Model path
    CHECKPOINT_PATH: "e2e_faster_rcnn_X-101-64x4d-FPN_2x-vlp.pkl"
    # cfg path
    CONFIG_PATH: "e2e_faster_rcnn_X-101-64x4d-FPN_2x-vlp.yaml"
    # dataset type 
    DATASET: "COCO" 
    # Max and min bounding boxes generated 
    MAX_BBOXES: 100
    MIN_BBOXES: 100
    # Datatype to store
    TYPE: float32
    # The name of the feature to extract
    FEATURE_NAME: "gpu_0/fc6"